### ISSUE TITLE
Merging more node types

### ISSUE THREAD

**Issue by erquhart** [syntax-tree/mdast-util-compact#4]
I'm wondering if it would be trivial to support merging certain inline nodes like `strong`, `emphasis`, and `delete`, optionally of course. When MDAST is created through a process that is external to Unified, undesirable idiosyncrasies like adjacent, identically typed nodes can occur, resulting in strange output like `**a****b****c**` instead of `**abc**`. This could be handled during the creation of the MDAST, apart from Unified, but this lib seems like a great place to handle it succinctly and in performant fashion.

It looks like this _could_ be as simple as extending the list of types to check for, but curious whether you foresee complications?

**Comment by wooorm** [comment]
Hi Shawn! 👋

That’s interesting! This could be made optional. Or it could be a different project. My thinking is that if it’ll add a bunch of weight, unneeded in remark-stringify, it should be a separate library. `mdast-util-compact` is also pretty tightly integrated with remark-stringify in [when it merges texts](https://github.com/syntax-tree/mdast-util-compact/blob/c754ee093e72de49fbd6093afd6d720bd211e645/index.js#L54). The text merging has to do with escaping.

`mdast-util-compact` merges `text`s, and `blockquote`s (in CM).

Reading through [`syntax-tree/mdast`](https://github.com/syntax-tree/mdast), I think it *could* make sense to merge `html`, `emphasis`, `strong`, `delete`, `InlineCode`, and to merge `text`s always.
A new thing could also clean up some other errors found in [`mdast-util-assert`](https://github.com/syntax-tree/mdast-util-assert), such as if a `root` occurs somewhere in the three.

**Comment by wooorm** [comment]
Do you have other cases that you run into?

**Comment by erquhart** [comment]
Yeah that makes sense. I haven't run into any other needs for merging, mostly looking at those "mark" style node types that apply to text. The immediate use is translating between Slate's AST and MDAST - Slate text nodes have an array of marks, which we're manually translating to the nested structure required for MDAST. We may need to handle it at the Slate -> MDAST level anyway to fully account for all cases.

**Comment by wooorm** [comment]
I think a slate to mdast thing makes sense! Could be its own library. I know that John is doing stuff for Slate in [blocks/blocks](https://github.com/blocks/blocks) as well, looks like that is using [orbiting/mdast](https://github.com/orbiting/mdast), which hosts several utilities for mdast <-> slate.

We can make a more “official” mdast-util-to-slate, if that’s needed?
This could maybe need node merging in a way that could benefit others. In which case I’d say make a new node merging utility? (but I’m suspecting that it would be specific to slate)

**Comment by erquhart** [comment]
An official utility would be amazing! A lot of work, though, Slate moves very fast with the breaking changes. That's also why I can't use the orbiting packages, they're about 16 months behind on Slate updates.

**Comment by wooorm** [comment]
As you’re saying Slate moves fast, I don’t think I could write or lead it, because I don’t use Slate really. 
But we can still make it, and host it here. It would need active support and usage from netlify-cms/you. But by hosting them here we can chime in as well, and if it’s “official”, probably more people will use it, leading to all the benefits of open source!

**Comment by wooorm** [comment]
btw, are there other things you’re doing with mdast that could be a utility here and be maintained here as well?

**Comment by wooorm** [comment]
Going to close this as I feel (see https://github.com/syntax-tree/mdast-util-compact/issues/4#issuecomment-492784808) this could be better as its own project.

**Comment by erquhart** [comment]
Makes sense, agreed.
